### ISSUE TITLE
FUNDING.yml and time

### ISSUE THREAD

**Issue by JohnMH** [TreacherousNexus/Wilber#15]
I would like to ask that you point to GIMP's own donating page, either instead of, or in addition to, your own. All of the actual work is being done upstream.

Additionally, I would like to address the issue of time, and make sure you know what you're getting into..

Renaming GIMP is going to take time. A lot of it. And changing certain parts, such as "top level code" (which I see you've got a ticket for) will make your fork incompatible with just about everything. What issue do you actually have with GIMP's name?

**Comment by JohnMH** [comment]
I will add that this is a personal request, and not required by any means. GIMP is, of course, Free Software, and you can do whatever you like.

**Comment by TreacherousNexus** [comment]
Thank you for your suggestion. My solution for now is to not point to any funding pages, as this repository is a placeholder and will likely be moved/renamed within the next week or so anyway. I'm currently talking to a group of other people who are interested in making a fork, so this will not be a "one man effort" :)

**Comment by TreacherousNexus** [comment]
As an aside, the full reasoning at this link, and I'm not going to retread it here: https://gitlab.gnome.org/GNOME/gimp/issues/3617

Also, it is not the responsibility of a fork to fund the upstream project.
